"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import type { FullAnalysis, AnalogySuggestion, BrokenBridgeReport, HybridSolution, ImpactProblem, ProblemStructure } from "@/lib/analogy-engine";
import { getCleanPaperUrl } from "@/lib/paper-utils";
import type { StructuralPattern } from "@/lib/seed-data";
import SolutionVisualizer from "@/components/SolutionVisualizer";
import styles from "./analyze.module.css";

/* ══════════════════════════════════════════════
   CONFIDENCE RING — SVG Circular Score
   ══════════════════════════════════════════════ */

function ConfidenceRing({ value, size = 64, label }: { value: number; size?: number; label?: string }) {
  const radius = (size - 8) / 2;
  const circumference = 2 * Math.PI * radius;
  const [animatedValue, setAnimatedValue] = useState(0);

  useEffect(() => {
    const timer = setTimeout(() => setAnimatedValue(value), 100);
    return () => clearTimeout(timer);
  }, [value]);

  const strokeDashoffset = circumference - (animatedValue * circumference);
  const percentage = Math.round(value * 100);

  // Color based on value
  const getColor = () => {
    if (value >= 0.8) return "var(--accent-green)";
    if (value >= 0.6) return "var(--accent-cyan)";
    if (value >= 0.4) return "var(--accent-amber)";
    return "var(--accent-red)";
  };

  return (
    <div className={styles.confidenceRing}>
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        {/* Background ring */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.06)"
          strokeWidth="4"
        />
        {/* Progress ring */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke={getColor()}
          strokeWidth="4"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          transform={`rotate(-90 ${size / 2} ${size / 2})`}
          style={{ transition: "stroke-dashoffset 1s cubic-bezier(0.22, 1, 0.36, 1)" }}
        />
      </svg>
      <div className={styles.confidenceValue}>
        <span className={styles.confidencePercent} style={{ color: getColor() }}>{percentage}%</span>
        {label && <span className={styles.confidenceLabel}>{label}</span>}
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   EXPORT BUTTON — Copy analysis to clipboard
   ══════════════════════════════════════════════ */

function ExportButton({ analysis }: { analysis: FullAnalysis }) {
  const [copied, setCopied] = useState(false);

  const handleExport = async () => {
    const lines: string[] = [
      "═══ UNIVERSAL ANALOGY ENGINE — ANALYSIS REPORT ═══",
      "",
      `PROBLEM: ${analysis.problem}`,
      "",
      "── STRUCTURAL EXTRACTION ──",
      `Summary: ${analysis.structure.summary}`,
      `Abstract Pattern: ${analysis.structure.abstractPattern}`,
      "",
      `Elements (${analysis.structure.elements.length}):`,
      ...analysis.structure.elements.map(el => `  • [${el.type}] ${el.name}: ${el.description}`),
      "",
      `── CROSS-DOMAIN ANALOGIES (${analysis.analogies.length}) ──`,
      ...analysis.analogies.map((a, i) => [
        `\n${i + 1}. ${a.sourceSystem} (${a.sourceDomain}) — ${Math.round(a.overallStrength * 100)}% match`,
        `   ${a.explanation}`,
        `   Mappings:`,
        ...a.mappings.map(m => `     ${m.sourceNode} → ${m.targetNode} (${Math.round(m.strength * 100)}%)`),
        `   Transferable Solutions:`,
        ...a.transferableSolutions.map(s => `     • ${s}`),
      ]).flat(),
      "",
      "── HYBRID SOLUTION ──",
      `Name: ${analysis.hybridSolution.name}`,
      `Description: ${analysis.hybridSolution.description}`,
      `Synthesis: ${analysis.hybridSolution.synthesis}`,
      "",
      `── GLOBAL IMPACT PROBLEMS (${analysis.impactProblems.length}) ──`,
      ...analysis.impactProblems.map(p => `  • [${p.status}] ${p.title} (${p.domain}) — ${Math.round(p.structuralSimilarity * 100)}% similar`),
      "",
      analysis.matchedPattern ? `── MATCHED PATTERN: #${analysis.matchedPattern.number} ${analysis.matchedPattern.name} ──` : "",
      "",
      "Generated by Universal Analogy Engine",
    ];

    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement("textarea");
      textarea.value = lines.join("\n");
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <button className={styles.exportBtn} onClick={handleExport} title="Copy analysis to clipboard">
      {copied ? (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--accent-green)" strokeWidth="2">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2" />
            <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
          </svg>
          Export
        </>
      )}
    </button>
  );
}

/* ══════════════════════════════════════════════
   ISOMORPHISM GRAPH — 2D Canvas Visualization
   ══════════════════════════════════════════════ */

function IsomorphismGraph({ analogy }: { analogy: AnalogySuggestion }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [hoveredMapping, setHoveredMapping] = useState<number | null>(null);
  const [selectedMapping, setSelectedMapping] = useState<number | null>(null);
  const nodesRef = useRef<{ source: { x: number; y: number }[]; target: { x: number; y: number }[] }>({ source: [], target: [] });
  const animFrameRef = useRef<number | null>(null);
  const progressRef = useRef(0);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width / 2; // scaled by 2 in CSS layout
    const h = canvas.height / 2;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    const mappings = analogy.mappings;
    const sourceX = w * 0.22;
    const targetX = w * 0.78;
    const nodeStartY = 50;
    const nodeGap = (h - 100) / Math.max(mappings.length - 1, 1);

    const sourceNodes: { x: number; y: number }[] = [];
    const targetNodes: { x: number; y: number }[] = [];

    mappings.forEach((_, i) => {
      const y = nodeStartY + i * nodeGap;
      sourceNodes.push({ x: sourceX, y });
      targetNodes.push({ x: targetX, y });
    });

    nodesRef.current = { source: sourceNodes, target: targetNodes };

    // Draw connection lines
    mappings.forEach((mapping, i) => {
      const isHovered = hoveredMapping === i;
      const isSelected = selectedMapping === i;
      const isActive = isHovered || isSelected;

      const gradient = ctx.createLinearGradient(sourceNodes[i].x, 0, targetNodes[i].x, 0);
      if (isActive) {
        gradient.addColorStop(0, `rgba(0, 229, 255, 0.9)`);
        gradient.addColorStop(0.5, `rgba(168, 85, 247, 0.9)`);
        gradient.addColorStop(1, `rgba(77, 124, 255, 0.9)`);
      } else {
        const opacity = 0.15 + mapping.strength * 0.25;
        gradient.addColorStop(0, `rgba(0, 229, 255, ${opacity})`);
        gradient.addColorStop(1, `rgba(77, 124, 255, ${opacity})`);
      }

      ctx.beginPath();
      ctx.moveTo(sourceNodes[i].x + 8, sourceNodes[i].y);
      const midX = (sourceNodes[i].x + targetNodes[i].x) / 2;
      ctx.bezierCurveTo(midX, sourceNodes[i].y, midX, targetNodes[i].y, targetNodes[i].x - 8, targetNodes[i].y);
      ctx.strokeStyle = gradient;
      ctx.lineWidth = isActive ? 3 : 1.5;
      ctx.stroke();

      // Flow particles along the bezier curve
      const particleCount = isActive ? 3 : 2;
      for (let p = 0; p < particleCount; p++) {
        const t = (progressRef.current + (p / particleCount) + i * 0.15) % 1;
        const p0x = sourceNodes[i].x + 8;
        const p0y = sourceNodes[i].y;
        const p1x = midX;
        const p1y = sourceNodes[i].y;
        const p2x = midX;
        const p2y = targetNodes[i].y;
        const p3x = targetNodes[i].x - 8;
        const p3y = targetNodes[i].y;

        const px = (1 - t) ** 3 * p0x + 3 * (1 - t) ** 2 * t * p1x + 3 * (1 - t) * t ** 2 * p2x + t ** 3 * p3x;
        const py = (1 - t) ** 3 * p0y + 3 * (1 - t) ** 2 * t * p1y + 3 * (1 - t) * t ** 2 * p2y + t ** 3 * p3y;

        ctx.beginPath();
        ctx.arc(px, py, isActive ? 3.5 : 2, 0, Math.PI * 2);
        ctx.fillStyle = isActive ? "rgba(0, 229, 255, 1)" : "rgba(0, 229, 255, 0.7)";
        ctx.fill();

        if (isActive) {
          ctx.beginPath();
          ctx.arc(px, py, 6, 0, Math.PI * 2);
          ctx.fillStyle = "rgba(0, 229, 255, 0.2)";
          ctx.fill();
        }
      }

      // Strength indicator at midpoint
      if (isActive) {
        const midY = (sourceNodes[i].y + targetNodes[i].y) / 2;
        ctx.font = "600 11px Inter";
        ctx.fillStyle = "rgba(0, 229, 255, 0.95)";
        ctx.textAlign = "center";
        ctx.fillText(`${Math.round(mapping.strength * 100)}%`, midX, midY - 8);
      }
    });

    // Draw source nodes
    mappings.forEach((mapping, i) => {
      const isActive = hoveredMapping === i || selectedMapping === i;
      const node = sourceNodes[i];

      ctx.beginPath();
      ctx.arc(node.x, node.y, isActive ? 7 : 5, 0, Math.PI * 2);
      ctx.fillStyle = isActive ? "rgba(0, 229, 255, 0.9)" : "rgba(0, 229, 255, 0.5)";
      ctx.fill();

      if (isActive) {
        ctx.beginPath();
        ctx.arc(node.x, node.y, 12, 0, Math.PI * 2);
        ctx.strokeStyle = "rgba(0, 229, 255, 0.3)";
        ctx.lineWidth = 1;
        ctx.stroke();
      }

      ctx.font = isActive ? "600 12px Inter" : "400 11px Inter";
      ctx.fillStyle = isActive ? "#e8eaf6" : "rgba(154, 160, 184, 0.9)";
      ctx.textAlign = "right";
      ctx.fillText(mapping.sourceNode, node.x - 18, node.y + 4);
    });

    // Draw target nodes
    mappings.forEach((mapping, i) => {
      const isActive = hoveredMapping === i || selectedMapping === i;
      const node = targetNodes[i];

      ctx.beginPath();
      ctx.arc(node.x, node.y, isActive ? 7 : 5, 0, Math.PI * 2);
      ctx.fillStyle = isActive ? "rgba(77, 124, 255, 0.9)" : "rgba(77, 124, 255, 0.5)";
      ctx.fill();

      if (isActive) {
        ctx.beginPath();
        ctx.arc(node.x, node.y, 12, 0, Math.PI * 2);
        ctx.strokeStyle = "rgba(77, 124, 255, 0.3)";
        ctx.lineWidth = 1;
        ctx.stroke();
      }

      ctx.font = isActive ? "600 12px Inter" : "400 11px Inter";
      ctx.fillStyle = isActive ? "#e8eaf6" : "rgba(154, 160, 184, 0.9)";
      ctx.textAlign = "left";
      ctx.fillText(mapping.targetNode, node.x + 18, node.y + 4);
    });

    // Domain labels
    ctx.font = "700 13px Outfit";
    ctx.fillStyle = "rgba(0, 229, 255, 0.7)";
    ctx.textAlign = "center";
    ctx.fillText(analogy.sourceDomain, sourceX, 25);

    ctx.fillStyle = "rgba(77, 124, 255, 0.7)";
    ctx.fillText("Your Problem", targetX, 25);
  }, [analogy, hoveredMapping, selectedMapping]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const rect = canvas.getBoundingClientRect();
    canvas.width = rect.width * 2;
    canvas.height = rect.height * 2;
    const ctx = canvas.getContext("2d");
    if (ctx) ctx.scale(2, 2);

    let lastTime = performance.now();
    const animate = (time: number) => {
      const dt = (time - lastTime) / 1000;
      lastTime = time;
      progressRef.current = (progressRef.current + dt * 0.25) % 1;
      draw();
      animFrameRef.current = requestAnimationFrame(animate);
    };

    animFrameRef.current = requestAnimationFrame(animate);

    return () => {
      if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
    };
  }, [draw]);

  useEffect(() => {
    draw();
  }, [draw, hoveredMapping, selectedMapping]);

  const handleCanvasMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const { source, target } = nodesRef.current;
    let found = -1;

    for (let i = 0; i < source.length; i++) {
      const distS = Math.sqrt((x - source[i].x) ** 2 + (y - source[i].y) ** 2);
      const distT = Math.sqrt((x - target[i].x) ** 2 + (y - target[i].y) ** 2);
      if (distS < 25 || distT < 25) {
        found = i;
        break;
      }
    }

    setHoveredMapping(found >= 0 ? found : null);
  };

  const handleCanvasClick = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const { source, target } = nodesRef.current;
    let found = -1;

    for (let i = 0; i < source.length; i++) {
      const distS = Math.sqrt((x - source[i].x) ** 2 + (y - source[i].y) ** 2);
      const distT = Math.sqrt((x - target[i].x) ** 2 + (y - target[i].y) ** 2);
      if (distS < 25 || distT < 25) {
        found = i;
        break;
      }
    }

    setSelectedMapping(found >= 0 ? (found === selectedMapping ? null : found) : null);
  };

  return (
    <div className={styles.isoGraph}>
      <div className={styles.isoHeader}>
        <h3 className={styles.isoTitle}>
          <span className={styles.isoDot} style={{ background: "var(--accent-cyan)" }} />
          {analogy.sourceSystem}
          <span className={styles.isoArrow}>⟷</span>
          <span className={styles.isoDot} style={{ background: "var(--accent-blue)" }} />
          Your Problem
        </h3>
        {analogy.url && (
          <a
            href={analogy.url}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "0.3rem",
              fontSize: "0.8rem",
              color: "#00e5ff",
              textDecoration: "none",
              background: "rgba(0, 229, 255, 0.1)",
              padding: "0.3rem 0.65rem",
              borderRadius: "6px",
              border: "1px solid rgba(0, 229, 255, 0.3)",
              fontWeight: 600,
              whiteSpace: "nowrap"
            }}
          >
            <span>View Paper</span> ↗
          </a>
        )}
        <div className={styles.isoStrength}>
          <span>Match Strength</span>
          <div className={styles.strengthMeter}>
            <div className={styles.strengthFill} style={{ width: `${analogy.overallStrength * 100}%` }} />
          </div>
          <span className={styles.strengthValue}>{Math.round(analogy.overallStrength * 100)}%</span>
        </div>
      </div>

      <canvas
        ref={canvasRef}
        className={styles.isoCanvas}
        onMouseMove={handleCanvasMove}
        onClick={handleCanvasClick}
        onMouseLeave={() => setHoveredMapping(null)}
      />

      {selectedMapping !== null && analogy.mappings[selectedMapping] && (
        <div className={styles.mappingReason}>
          <div className={styles.mappingReasonHeader}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--accent-cyan)" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="16" x2="12" y2="12" />
              <line x1="12" y1="8" x2="12" y2="8" />
            </svg>
            Why this mapping?
          </div>
          <p>{analogy.mappings[selectedMapping].reason}</p>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════
   5-PART DETAILED ANALOGY BREAKDOWN PANEL
   ══════════════════════════════════════════════ */

function DetailedAnalogyBreakdown({ analogy }: { analogy: AnalogySuggestion }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={styles.analogyAccordion}>
      <button
        className={`${styles.analogyAccordionToggle} ${isOpen ? styles.analogyAccordionToggleOpen : ""}`}
        onClick={(e) => {
          e.stopPropagation();
          setIsOpen(!isOpen);
        }}
      >
        <span className={styles.analogyAccordionLabel}>
          {isOpen ? "Hide Details" : "View Details"}
        </span>
        <span className={`${styles.analogyAccordionChevron} ${isOpen ? styles.analogyAccordionChevronOpen : ""}`}>
          ›
        </span>
      </button>

      <div className={`${styles.analogyAccordionContent} ${isOpen ? styles.analogyAccordionContentOpen : ""}`}>
        <div className={styles.detailedAnalogyBreakdown}>
          {/* 1. Target Research Problem Context */}
          <div className={styles.breakdownBox}>
            <div className={styles.breakdownHeader}>
              <span className={styles.breakdownIcon}>🎯</span>
              <span>What Problem Was Solved ({analogy.sourceDomain})</span>
            </div>
            <p className={styles.breakdownText}>
              {analogy.targetProblem || analogy.explanation}
            </p>
          </div>

          {/* 2. Root Mechanism */}
          {analogy.problemMechanism && (
            <div className={styles.breakdownBox}>
              <div className={styles.breakdownHeader}>
                <span className={styles.breakdownIcon}>⚡</span>
                <span>Why It Happens</span>
              </div>
              <p className={styles.breakdownText}>{analogy.problemMechanism}</p>
            </div>
          )}

          {/* 3. Source Domain Solution */}
          {analogy.targetSolution && (
            <div className={styles.breakdownBox}>
              <div className={styles.breakdownHeader}>
                <span className={styles.breakdownIcon}>🔧</span>
                <span>How They Fixed It</span>
              </div>
              <p className={styles.breakdownText}>{analogy.targetSolution}</p>
            </div>
          )}

          {/* 4. Why The Two Problems Match */}
          {analogy.structuralComparison && (
            <div className={styles.breakdownBox}>
              <div className={styles.breakdownHeader}>
                <span className={styles.breakdownIcon}>🔀</span>
                <span>Why These Two Problems Match</span>
              </div>
              <p className={styles.breakdownText}>{analogy.structuralComparison}</p>
            </div>
          )}

          {/* 5. How To Apply This To Your Problem */}
          {analogy.detailedTransferSolution && (
            <div className={styles.breakdownBoxHighlight}>
              <div className={styles.breakdownHeaderHighlight}>
                <span className={styles.breakdownIcon}>🚀</span>
                <span>How To Apply This To Your Problem</span>
              </div>
              <div className={styles.breakdownTextHighlight}>
                {analogy.detailedTransferSolution}
              </div>
            </div>
          )}

          {/* Research Paper Link Button */}
          <div style={{ marginTop: "1rem", paddingTop: "0.75rem", borderTop: "1px solid rgba(255, 255, 255, 0.08)", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "0.5rem" }}>
            <span style={{ fontSize: "0.8rem", color: "#94a3b8" }}>📄 Research Paper: <strong>{analogy.sourceSystem}</strong></span>
            <a
              href={getCleanPaperUrl(analogy.sourceSystem, analogy.url)}
              target="_blank"
              rel="noopener noreferrer"
              className={styles.paperBtn}
            >
              View Published Research Paper ↗
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   STRUCTURAL EXTRACTION PANEL
   ══════════════════════════════════════════════ */

function StructurePanel({ structure }: { structure: ProblemStructure }) {
  const typeColors: Record<string, string> = {
    entity: "cyan",
    constraint: "amber",
    goal: "green",
    flow: "blue",
    bottleneck: "red",
    feedback: "purple",
    dependency: "amber",
    risk: "red",
  };

  const typeIcons: Record<string, string> = {
    entity: "⬡",
    constraint: "⊘",
    goal: "◎",
    flow: "→",
    bottleneck: "⊗",
    feedback: "↻",
    dependency: "⊷",
    risk: "⚠",
  };

  return (
    <div className={styles.structPanel}>
      <h3 className={styles.panelTitle}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-cyan)" strokeWidth="2">
          <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
          <line x1="12" y1="22" x2="12" y2="15.5" />
          <polyline points="22 8.5 12 15.5 2 8.5" />
        </svg>
        Structural Extraction
      </h3>
      <p className={styles.structSummary}>{structure.summary}</p>

      <div className={styles.structAbstract}>
        <span className={styles.structAbstractLabel}>Abstract Pattern:</span>
        <span className={styles.structAbstractValue}>{structure.abstractPattern}</span>
      </div>

      <div className={styles.elementGrid}>
        {structure.elements.map((el, i) => (
          <div key={i} className={styles.element}>
            <div className={styles.elementHeader}>
              <span className={styles.elementIcon}>{typeIcons[el.type] || "•"}</span>
              <span className={`tag tag-${typeColors[el.type] || "cyan"}`}>{el.type}</span>
            </div>
            <span className={styles.elementName}>{el.name}</span>
            <span className={styles.elementDesc}>{el.description}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   BROKEN BRIDGE REPORT
   ══════════════════════════════════════════════ */

function BrokenBridgePanel({ report }: { report: BrokenBridgeReport }) {
  const [expandedSection, setExpandedSection] = useState<string | null>("direct");

  const toggleSection = (id: string) => {
    setExpandedSection(expandedSection === id ? null : id);
  };

  const totalItems = report.directTransfers.length + report.adaptedTransfers.length + report.failures.length;

  return (
    <div className={styles.bridgePanel}>
      <h3 className={styles.panelTitle}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-red)" strokeWidth="2">
          <path d="M12 9v2m0 4h.01M5 3h14a2 2 0 012 2v14a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2z" />
        </svg>
        Broken Bridge Analysis
      </h3>

      {/* Severity Summary Bar */}
      <div className={styles.severitySummary}>
        <div className={styles.severityBar}>
          {totalItems > 0 && (
            <>
              <div
                className={styles.severitySegment}
                style={{
                  width: `${(report.directTransfers.length / totalItems) * 100}%`,
                  background: "var(--accent-green)",
                }}
              />
              <div
                className={styles.severitySegment}
                style={{
                  width: `${(report.adaptedTransfers.length / totalItems) * 100}%`,
                  background: "var(--accent-amber)",
                }}
              />
              <div
                className={styles.severitySegment}
                style={{
                  width: `${(report.failures.length / totalItems) * 100}%`,
                  background: "var(--accent-red)",
                }}
              />
            </>
          )}
        </div>
        <div className={styles.severityLabels}>
          <span style={{ color: "var(--accent-green)" }}>{report.directTransfers.length} transferable</span>
          <span style={{ color: "var(--accent-amber)" }}>{report.adaptedTransfers.length} adapted</span>
          <span style={{ color: "var(--accent-red)" }}>{report.failures.length} breaks</span>
        </div>
      </div>

      {/* Direct Transfers */}
      <div className={styles.bridgeSection}>
        <button
          className={`${styles.bridgeSectionTitle} ${styles.bridgeSectionToggle}`}
          onClick={() => toggleSection("direct")}
        >
          <span className={styles.bridgeIcon} style={{ color: "var(--accent-green)" }}>✓</span>
          Direct Transfers
          <span className={styles.bridgeCount}>{report.directTransfers.length}</span>
          <span className={`${styles.bridgeChevron} ${expandedSection === "direct" ? styles.bridgeChevronOpen : ""}`}>›</span>
        </button>
        {expandedSection === "direct" && report.directTransfers.map((t, i) => (
          <div key={i} className={styles.bridgeItem}>
            <span className={styles.bridgeItemName}>{t.element}</span>
            <span className={styles.bridgeItemDesc}>{t.explanation}</span>
          </div>
        ))}
      </div>

      {/* Adapted Transfers */}
      <div className={styles.bridgeSection}>
        <button
          className={`${styles.bridgeSectionTitle} ${styles.bridgeSectionToggle}`}
          onClick={() => toggleSection("adapted")}
        >
          <span className={styles.bridgeIcon} style={{ color: "var(--accent-amber)" }}>⚠</span>
          Transfers with Adaptation
          <span className={styles.bridgeCount}>{report.adaptedTransfers.length}</span>
          <span className={`${styles.bridgeChevron} ${expandedSection === "adapted" ? styles.bridgeChevronOpen : ""}`}>›</span>
        </button>
        {expandedSection === "adapted" && report.adaptedTransfers.map((t, i) => (
          <div key={i} className={styles.bridgeItem}>
            <span className={styles.bridgeItemName}>{t.element}</span>
            <span className={styles.bridgeItemDesc}>{t.adaptation}</span>
            <span className={styles.bridgeRisk}>Risk: {t.risk}</span>
          </div>
        ))}
      </div>

      {/* Failures */}
      <div className={styles.bridgeSection}>
        <button
          className={`${styles.bridgeSectionTitle} ${styles.bridgeSectionToggle}`}
          onClick={() => toggleSection("failures")}
        >
          <span className={styles.bridgeIcon} style={{ color: "var(--accent-red)" }}>✗</span>
          Structural Breaks
          <span className={styles.bridgeCount}>{report.failures.length}</span>
          <span className={`${styles.bridgeChevron} ${expandedSection === "failures" ? styles.bridgeChevronOpen : ""}`}>›</span>
        </button>
        {expandedSection === "failures" && report.failures.map((f, i) => (
          <div key={i} className={`${styles.bridgeItem} ${styles.bridgeFailure}`}>
            <div className={styles.bridgeFailHeader}>
              <span className={styles.bridgeItemName}>{f.breakPoint}</span>
              <span className={`tag tag-${f.severity === "high" ? "red" : f.severity === "medium" ? "amber" : "blue"}`}>
                {f.severity}
              </span>
            </div>
            <span className={styles.bridgeItemDesc}>{f.reason}</span>
            <div className={styles.bridgeInnovation}>
              <span className={styles.bridgeInnovationLabel}>💡 Innovation at the break:</span>
              <span>{f.innovation}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Innovation Opportunities */}
      {report.innovationOpportunities.length > 0 && (
        <div className={styles.bridgeSection}>
          <button
            className={`${styles.bridgeSectionTitle} ${styles.bridgeSectionToggle}`}
            onClick={() => toggleSection("innovation")}
          >
            <span className={styles.bridgeIcon} style={{ color: "var(--accent-purple)" }}>✦</span>
            Innovation Opportunities
            <span className={styles.bridgeCount}>{report.innovationOpportunities.length}</span>
            <span className={`${styles.bridgeChevron} ${expandedSection === "innovation" ? styles.bridgeChevronOpen : ""}`}>›</span>
          </button>
          {expandedSection === "innovation" && (
            <ul className={styles.innovationList}>
              {report.innovationOpportunities.map((opp, i) => (
                <li key={i}>{opp}</li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════
   HYBRID SOLUTION COMPOSER
   ══════════════════════════════════════════════ */

function HybridPanel({ solution }: { solution: HybridSolution }) {
  const domainColors = ["cyan", "purple", "amber", "green", "blue"];
  const [expandedComponent, setExpandedComponent] = useState<number | null>(null);

  return (
    <div className={styles.hybridPanel}>
      <h3 className={styles.panelTitle}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-purple)" strokeWidth="2">
          <path d="M12 2L2 7l10 5 10-5-10-5z" />
          <path d="M2 17l10 5 10-5" />
          <path d="M2 12l10 5 10-5" />
        </svg>
        Hybrid Solution
      </h3>

      <div className={styles.hybridName}>{solution.name}</div>
      <p className={styles.hybridDesc}>{solution.description}</p>

      {/* Domain Contribution Bar */}
      <div className={styles.domainContribBar}>
        {solution.components.map((comp, i) => (
          <div
            key={i}
            className={styles.domainContribSegment}
            style={{
              flex: 1,
              background: `var(--accent-${domainColors[i % domainColors.length]})`,
              opacity: expandedComponent === i ? 1 : 0.6,
            }}
            title={comp.sourceDomain}
          />
        ))}
      </div>
      <div className={styles.domainContribLabels}>
        {solution.components.map((comp, i) => (
          <span key={i} style={{ color: `var(--accent-${domainColors[i % domainColors.length]})`, flex: 1, textAlign: "center", fontSize: "0.65rem" }}>
            {comp.sourceDomain}
          </span>
        ))}
      </div>

      <div className={styles.hybridComponents}>
        <h4 className={styles.hybridComponentsTitle}>Component Sources</h4>
        {solution.components.map((comp, i) => (
          <button
            key={i}
            className={`${styles.hybridComponent} ${expandedComponent === i ? styles.hybridComponentExpanded : ""}`}
            onClick={() => setExpandedComponent(expandedComponent === i ? null : i)}
          >
            <div className={styles.hybridComponentHeader}>
              <span className={`tag tag-${domainColors[i % domainColors.length]}`}>
                {comp.sourceDomain}
              </span>
              <span className={styles.hybridExpandIcon}>{expandedComponent === i ? "−" : "+"}</span>
            </div>
            <div className={styles.hybridPrinciple}>{comp.principle}</div>
            {expandedComponent === i && (
              <div className={styles.hybridContribution}>{comp.contribution}</div>
            )}
          </button>
        ))}
      </div>

      <div className={styles.hybridSynthesis}>
        <h4>⚡ Synthesis</h4>
        <p>{solution.synthesis}</p>
      </div>

      <div className={styles.hybridRisks}>
        <h4>⚠ Risks</h4>
        <ul>
          {solution.risks.map((risk, i) => (
            <li key={i}>{risk}</li>
          ))}
        </ul>
      </div>

      <div className={styles.hybridTesting}>
        <h4>🧪 Testing Recommendations</h4>
        <ul>
          {solution.testingRecommendations.map((rec, i) => (
            <li key={i}>{rec}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   IMPACT PROBLEM FINDER
   ══════════════════════════════════════════════ */

function ImpactPanel({ problems }: { problems: ImpactProblem[] }) {
  const statusColors: Record<string, string> = {
    solved: "green",
    "partially-solved": "amber",
    unsolved: "red",
    untried: "purple",
  };

  const impactColors: Record<string, string> = {
    low: "blue",
    medium: "amber",
    high: "red",
    critical: "red",
  };

  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const avgFeasibility = problems.length
    ? Math.round((problems.reduce((a, p) => a + p.transferFeasibility, 0) / problems.length) * 100)
    : 0;

  return (
    <div className={styles.impactPanel}>
      <h3 className={styles.panelTitle}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-green)" strokeWidth="2">
          <circle cx="12" cy="12" r="10" />
          <line x1="2" y1="12" x2="22" y2="12" />
          <path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z" />
        </svg>
        Same-Structure Global Problems
      </h3>

      <div className={styles.impactHeaderSummary}>
        <div>
          <p className={styles.impactSubtitle}>
            These high-impact challenges share the exact same structural pattern as your problem.
            Solutions transferred from your system can directly address them.
          </p>
        </div>
        <div className={styles.impactSummaryBadge}>
          <span className={styles.impactSummaryNum}>{avgFeasibility}%</span>
          <span className={styles.impactSummaryText}>Avg Transfer Feasibility</span>
        </div>
      </div>

      <div className={styles.impactGrid}>
        {problems.map((problem, i) => (
          <div
            key={i}
            className={`${styles.impactCard} ${expandedIndex === i ? styles.impactCardExpanded : ""}`}
          >
            <div className={styles.impactCardHeader}>
              <span className={styles.impactTitle}>{problem.title}</span>
              <div className={styles.impactTags}>
                <span className={`tag tag-${statusColors[problem.status]}`}>
                  {problem.status.replace("-", " ")}
                </span>
                <span className={`tag tag-${impactColors[problem.socialImpact]}`}>
                  {problem.socialImpact} impact
                </span>
              </div>
            </div>

            <div className={styles.impactDomain}>{problem.domain}</div>
            <p className={styles.impactDesc}>{problem.description}</p>

            <div className={styles.impactRings}>
              <ConfidenceRing value={problem.structuralSimilarity} size={54} label="Similarity" />
              <ConfidenceRing value={problem.transferFeasibility} size={54} label="Feasibility" />
            </div>

            <div className={styles.impactScale}>{problem.scale}</div>

            <button
              className={styles.impactExpandBtn}
              onClick={() => setExpandedIndex(expandedIndex === i ? null : i)}
            >
              {expandedIndex === i ? "Hide Transfer Details ▲" : "View Transfer Details ▼"}
            </button>

            {expandedIndex === i && (
              <div className={styles.impactDetails}>
                <div className={styles.impactDetailItem}>
                  <span className={styles.impactDetailLabel}>Why structure maps:</span>
                  <p>Shares identical flow dynamics, bottleneck points, and regulatory feedback loops.</p>
                </div>
                <div className={styles.impactDetailItem}>
                  <span className={styles.impactDetailLabel}>Recommended Transfer Step:</span>
                  <p>Adapt the hybrid mechanism to re-route resource allocation under peak demand spikes.</p>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   PATTERN MATCH PANEL
   ══════════════════════════════════════════════ */

function PatternPanel({ pattern }: { pattern: StructuralPattern }) {
  return (
    <div className={styles.patternPanel}>
      <h3 className={styles.panelTitle}>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-amber)" strokeWidth="2">
          <rect x="3" y="3" width="7" height="7" />
          <rect x="14" y="3" width="7" height="7" />
          <rect x="14" y="14" width="7" height="7" />
          <rect x="3" y="14" width="7" height="7" />
        </svg>
        Universal Pattern Match
      </h3>

      <div className={styles.patternHeader}>
        <span className={styles.patternNumber}>Pattern #{pattern.number}</span>
        <span className={styles.patternName}>{pattern.name}</span>
      </div>

      <p className={styles.patternDesc}>{pattern.abstractDescription}</p>

      <div className={styles.patternDomains}>
        <h4>Appears in {pattern.domainCount} domains:</h4>
        <div className={styles.patternExamples}>
          {pattern.examples.slice(0, 6).map((ex, i) => (
            <div key={i} className={styles.patternExample}>
              <span className={`tag tag-cyan`}>{ex.domain}</span>
              <span className={styles.patternExProblem}>{ex.problem}</span>
            </div>
          ))}
        </div>
      </div>

      <div className={styles.patternSolutions}>
        <h4>Common Solutions:</h4>
        <ul>
          {pattern.commonSolutions.map((sol, i) => (
            <li key={i}>{sol}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   LOADING STATE
   ══════════════════════════════════════════════ */

function LoadingState() {
  const steps = [
    "Extracting problem structure...",
    "Identifying entities, constraints, and flows...",
    "Searching across 15+ knowledge domains...",
    "Finding structural matches in biology...",
    "Finding structural matches in engineering...",
    "Finding structural matches in ecology...",
    "Computing isomorphic mappings...",
    "Analyzing broken bridges...",
    "Synthesizing hybrid solution...",
    "Discovering same-structure problems...",
    "Matching to Universal Pattern Library...",
    "Compiling analysis report...",
  ];

  const [currentStep, setCurrentStep] = useState(0);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentStep((prev) => {
        if (prev < steps.length - 1) return prev + 1;
        return prev;
      });
      setProgress((prev) => Math.min(prev + 8 + Math.random() * 5, 100));
    }, 400);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className={styles.loading}>
      <div className={styles.loadingOrb}>
        <div className={styles.loadingOrbInner} />
        <div className={styles.loadingOrbRing} />
        <div className={styles.loadingOrbRing2} />
      </div>
      <h2 className={styles.loadingTitle}>Analyzing Problem Structure</h2>
      <div className={styles.loadingProgress}>
        <div className={styles.loadingProgressBar}>
          <div className={styles.loadingProgressFill} style={{ width: `${progress}%` }} />
        </div>
        <span className={styles.loadingPercent}>{Math.round(progress)}%</span>
      </div>
      <div className={styles.loadingSteps}>
        {steps.slice(0, currentStep + 1).map((step, i) => (
          <div
            key={i}
            className={`${styles.loadingStep} ${i === currentStep ? styles.loadingStepActive : styles.loadingStepDone}`}
          >
            <span className={styles.loadingStepIcon}>
              {i < currentStep ? "✓" : i === currentStep ? "◌" : "○"}
            </span>
            {step}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════
   MAIN ANALYSIS PAGE
   ══════════════════════════════════════════════ */

export default function AnalyzePage() {
  const [analysis, setAnalysis] = useState<FullAnalysis | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<string>("overview");
  const [selectedAnalogyIdx, setSelectedAnalogyIdx] = useState(0);
  const router = useRouter();

  useEffect(() => {
    const problem = sessionStorage.getItem("analysisProblem");
    if (!problem) {
      router.push("/");
      return;
    }

    const fetchAnalysis = async () => {
      setIsLoading(true);
      try {
        // Add a deliberate delay for the loading animation
        await new Promise((resolve) => setTimeout(resolve, 5000));

        const res = await fetch("/api/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ problem }),
        });

        if (!res.ok) throw new Error("Analysis failed");

        const data = await res.json();
        setAnalysis(data);
      } catch (err) {
        setError("Failed to analyze problem. Please try again.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchAnalysis();
  }, [router]);

  if (isLoading) {
    return (
      <main className={styles.main}>
        <LoadingState />
      </main>
    );
  }

  if (error || !analysis) {
    return (
      <main className={styles.main}>
        <div className={styles.error}>
          <h2>Analysis Error</h2>
          <p>{error || "No analysis data available."}</p>
          <button className="btn-primary" onClick={() => router.push("/")}>
            Try Again
          </button>
        </div>
      </main>
    );
  }

  const tabs = [
    { id: "overview", label: "Overview", icon: "◎" },
    { id: "graph", label: "Isomorphism Graph", icon: "⬡" },
    { id: "bridge", label: "Broken Bridge", icon: "⊗" },
    { id: "hybrid", label: "Hybrid Solution", icon: "⚡" },
    { id: "impact", label: "Global Impact", icon: "🌍" },
    { id: "pattern", label: "Pattern Match", icon: "📐" },
  ];

  return (
    <main className={styles.main}>
      {/* ── Top Bar ── */}
      <div className={styles.topBar}>
        <button className={styles.backBtn} onClick={() => router.push("/")}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <polyline points="15 18 9 12 15 6" />
          </svg>
          New Analysis
        </button>
        <div className={styles.topBarProblem}>
          {analysis.problem.length > 80
            ? analysis.problem.substring(0, 80) + "..."
            : analysis.problem}
        </div>
        <div className={styles.topBarActions}>
          <span style={{ fontSize: "0.75rem", background: "rgba(16, 185, 129, 0.15)", border: "1px solid rgba(16, 185, 129, 0.4)", color: "#34d399", padding: "0.3rem 0.65rem", borderRadius: "12px", display: "inline-flex", alignItems: "center", gap: "0.4rem", fontWeight: 600 }}>
            <span>⚡</span> Mapped Analogies Auto-Updated
          </span>
          <ExportButton analysis={analysis} />
        </div>
      </div>

      {/* ── Tab Navigation ── */}
      <div className={styles.tabBar}>
        {tabs.map((tab) => (
          <button
            key={tab.id}
            className={`${styles.tab} ${activeTab === tab.id ? styles.tabActive : ""}`}
            onClick={() => setActiveTab(tab.id)}
          >
            <span className={styles.tabIcon}>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* ── Content Panels ── */}
      <div className={styles.content}>
        {activeTab === "overview" && (
          <div className={styles.overview}>
            {/* Quick Stats Row */}
            <div className={styles.quickStats}>
              <div className={styles.quickStatItem}>
                <ConfidenceRing
                  value={analysis.analogies.reduce((acc, a) => Math.max(acc, a.overallStrength), 0)}
                  size={72}
                  label="Best Match"
                />
              </div>
              <div className={styles.quickStatItem}>
                <ConfidenceRing
                  value={analysis.analogies.length / 5}
                  size={72}
                  label="Coverage"
                />
              </div>
              <div className={styles.quickStatItem}>
                <div className={styles.quickStatText}>
                  <span className={styles.quickStatNumber}>{analysis.analogies.length}</span>
                  <span className={styles.quickStatLabel}>Analogies</span>
                </div>
              </div>
              <div className={styles.quickStatItem}>
                <div className={styles.quickStatText}>
                  <span className={styles.quickStatNumber}>{analysis.structure.elements.length}</span>
                  <span className={styles.quickStatLabel}>Elements</span>
                </div>
              </div>
              <div className={styles.quickStatItem}>
                <div className={styles.quickStatText}>
                  <span className={styles.quickStatNumber}>{analysis.impactProblems.length}</span>
                  <span className={styles.quickStatLabel}>Impact Problems</span>
                </div>
              </div>
            </div>

            {/* Structure Panel */}
            <StructurePanel structure={analysis.structure} />

            {/* Analogy Cards */}
            <div className={styles.analogySection}>
              <h3 className={styles.panelTitle}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-blue)" strokeWidth="2">
                  <path d="M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z" />
                </svg>
                Cross-Domain Analogies Found
              </h3>
              <div className={styles.analogyCards}>
                {analysis.analogies.map((analogy, i) => (
                  <div
                    key={analogy.id}
                    className={`${styles.analogyCard} ${selectedAnalogyIdx === i ? styles.analogyCardActive : ""}`}
                    onClick={() => {
                      setSelectedAnalogyIdx(i);
                      setActiveTab("graph");
                    }}
                  >
                    <div className={styles.analogyCardHeader}>
                      <span className={`tag tag-cyan`}>{analogy.sourceDomain}</span>
                      <span className={styles.analogyStrength}>
                        {Math.round(analogy.overallStrength * 100)}%
                      </span>
                    </div>
                    <h4 className={styles.analogyShortName}>{analogy.analogyName || analogy.sourceSystem}</h4>
                    {analogy.analogyName && (
                      <div className={styles.analogySubtitle}>{analogy.sourceSystem}</div>
                    )}

                    <div className={styles.analogyCardMappings}>
                      {analogy.mappings.slice(0, 3).map((m, j) => (
                        <div key={j} className={styles.miniMapping}>
                          <span>{m.sourceNode}</span>
                          <span className={styles.miniArrow}>→</span>
                          <span>{m.targetNode}</span>
                        </div>
                      ))}
                      {analogy.mappings.length > 3 && (
                        <span className={styles.moreText}>
                          +{analogy.mappings.length - 3} more mappings
                        </span>
                      )}
                    </div>
                    <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.75rem", flexWrap: "wrap" }}>
                      <button
                        className={styles.viewGraphBtn}
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedAnalogyIdx(i);
                          setActiveTab("graph");
                        }}
                      >
                        View Isomorphism Graph →
                      </button>
                      <a
                        href={getCleanPaperUrl(analogy.sourceSystem, analogy.url)}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={styles.paperBtn}
                        onClick={(e) => e.stopPropagation()}
                      >
                        📄 Open Paper ↗
                      </a>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {activeTab === "graph" && analysis.analogies[selectedAnalogyIdx] && (
          <div className={styles.graphTab}>
            {/* Analogy Selector */}
            <div className={styles.analogySelector}>
              {analysis.analogies.map((a, i) => (
                <button
                  key={a.id}
                  className={`${styles.analogySelectorBtn} ${i === selectedAnalogyIdx ? styles.analogySelectorActive : ""}`}
                  onClick={() => setSelectedAnalogyIdx(i)}
                >
                  <span className={`tag tag-cyan`}>{a.sourceDomain}</span>
                  {a.analogyName || a.sourceSystem}
                </button>
              ))}
            </div>

            {/* Inspiring Research Paper Card */}
            <div className={styles.paperBannerCard}>
              <div className={styles.paperBannerInfo}>
                <span style={{ fontSize: "0.72rem", color: "#38bdf8", fontWeight: 700, textTransform: "uppercase" }}>
                  📄 Inspiring Research Paper ({analysis.analogies[selectedAnalogyIdx].sourceDomain})
                </span>
                <span className={styles.paperBannerTitle}>{analysis.analogies[selectedAnalogyIdx].sourceSystem}</span>
              </div>
              <a
                href={getCleanPaperUrl(analysis.analogies[selectedAnalogyIdx].sourceSystem, analysis.analogies[selectedAnalogyIdx].url)}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.paperBtn}
                style={{ padding: "0.6rem 1.2rem", fontSize: "0.85rem" }}
              >
                View Published Research Paper ↗
              </a>
            </div>

            <IsomorphismGraph analogy={analysis.analogies[selectedAnalogyIdx]} />

            <SolutionVisualizer analogy={analysis.analogies[selectedAnalogyIdx]} />

            <DetailedAnalogyBreakdown analogy={analysis.analogies[selectedAnalogyIdx]} />

            {/* Transferable Solutions */}
            <div className={styles.transferSolutions}>
              <h4 className={styles.transferTitle}>Transferable Solutions</h4>
              {analysis.analogies[selectedAnalogyIdx].transferableSolutions.map((sol, i) => (
                <div key={i} className={styles.transferItem}>
                  <span className={styles.transferNum}>{String(i + 1).padStart(2, "0")}</span>
                  <span>{sol}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === "bridge" && analysis.brokenBridgeReports.length > 0 && (
          <BrokenBridgePanel report={analysis.brokenBridgeReports[0]} />
        )}

        {activeTab === "hybrid" && (
          <HybridPanel solution={analysis.hybridSolution} />
        )}

        {activeTab === "impact" && (
          <ImpactPanel problems={analysis.impactProblems} />
        )}

        {activeTab === "pattern" && analysis.matchedPattern && (
          <PatternPanel pattern={analysis.matchedPattern} />
        )}
      </div>
    </main>
  );
}
